export const REFRESH_DATA = 'REFRESH_DATA';
export const NEW_POST = 'NEW_POST';

export const FETCH_LATEST_NEWS = "FETCH_LATEST_NEWS";
export const ADD_NEWS = "ADD_NEWS";
export const READ_LATEST = "READ_LATEST";

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_HISTORY_BY_COUNTRY = "GET_HISTORY_BY_COUNTRY";
export const GET_DETAILS_BY_COUNTRY = "GET_DETAILS_BY_COUNTRY";
